#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

export DASHSCOPE_API_KEY="${DASHSCOPE_API_KEY:-mock-not-used}" 
export DASHSCOPE_MOCK_ENABLED="${DASHSCOPE_MOCK_ENABLED:-true}"
export DASHSCOPE_MOCK_RESPONSE="${DASHSCOPE_MOCK_RESPONSE:-这是本地压测Mock回复。}"
export DASHSCOPE_MOCK_FIRST_TOKEN_DELAY_MS="${DASHSCOPE_MOCK_FIRST_TOKEN_DELAY_MS:-120}"
export DASHSCOPE_MOCK_CHUNK_DELAY_MS="${DASHSCOPE_MOCK_CHUNK_DELAY_MS:-60}"
export DASHSCOPE_MOCK_CHUNK_SIZE="${DASHSCOPE_MOCK_CHUNK_SIZE:-8}"

echo "DASHSCOPE_MOCK_ENABLED=${DASHSCOPE_MOCK_ENABLED}"
echo "DASHSCOPE_MOCK_FIRST_TOKEN_DELAY_MS=${DASHSCOPE_MOCK_FIRST_TOKEN_DELAY_MS}"
echo "DASHSCOPE_MOCK_CHUNK_DELAY_MS=${DASHSCOPE_MOCK_CHUNK_DELAY_MS}"
echo "DASHSCOPE_MOCK_CHUNK_SIZE=${DASHSCOPE_MOCK_CHUNK_SIZE}"

mvn spring-boot:run
